### ISSUE TITLE
Register file and memory Dff

### ISSUE THREAD

**Issue by kereng1** [kereng1/mips_poc#10]
when we create the Register file and memory 
we wright `DFF (registers, next_registers, clk); 
that we difined above in the code.

these FF have more than one input and output 
so my question is are these FF (the reg_file and memo) are alot of D ff together? and if so where do we support it in the code? and where do we difine the inputs to these FF?

lets say if this is the regfile:
 logic [31:0] registers[31:0];
logic [31:0] next_registers[31:0];

i need clirifacations on this pls.
if you have 10 min to zoom i would really like that! @amichai-bd

**Comment by amichai-bd** [comment]
There are many ways to code a memory array with a single write port..
maybe the way i showed you is less understood.
I will write multple examples for you to read though and understand.



Examlple:

```systemverilog
`DFF(regsiter_file, next_register_file, clk)
always_cobb begin 
    next_regster_file = register_file;
    if (reg_wr_en) next_register_file[rd] = reg_wr_data
end //always
```


Other example - note that this is an "en" DFF..
```systemverilog
`EN_DFF(regsiter_file[rd] , reg_wr_data, clk, reg_wr_en )
```

**Comment by amichai-bd** [comment]
Another example:
```systemverilog
`DFF(register_file, next_register_file, clk)
always_comb begin
   for (int i = 0; i < 32; i++) begin
       next_register_file[i] = (reg_wr_en && (rd == i)) ? reg_wr_data : register_file[i];
   end
end
```

**Comment by amichai-bd** [comment]
Or this:
```systemverilog
`DFF(register_file, next_register_file, clk)
always_comb begin
   next_register_file= register_file;  //default no change
   for (int i = 0; i < 32; i++) begin
       if((rd == i))   next_register_file[i] = reg_wr_data;
   end
end
```

**Comment by kereng1** [comment]
ok, now its clear 
thank you
