### ISSUE TITLE
DECODE:what is the rf_write?

### ISSUE THREAD

**Issue by kereng1** [kereng1/mips_poc#6]
in the decode - the writing prossess:

always_comb begin : rf_write
    next_registers = registers;      //default
    if (RegWrite) begin
        next_registers[write_ptr] = write_data_reg;
    end
    
- [x] in the decode - the wruting prossess there is a always_comb ,what is the rf_write variable there (reference to the ss mips drawing)?
- [ ] and is the ' next_registers ' referenced to 'Write register' in the regfile

**Comment by amichai-bd** [comment]
the "rf_write" in the fist line:
```systemverilog
always_comb begin : rf_write
```
is just the name of the always block.
This is not mandatory. you are allowed not to write a always_com block name.. 
But it's recommended just for clarity.

the "next_registers" is just a coding style to make sure we understand that the registers update from next_register->register.

By default we don't need to update anything so we simply:
```systremverilog 
next_registers = registers; //default

```
And then if we have a RegWrite we want to override one of the register values:
```systemverilog
if (RegWrite) begin
next_registers[write_ptr] = write_data_reg;
end
```

**Comment by kereng1** [comment]
Maybe i miss understood you @amichai-bd 
we defined a: logic [31:0] next_registers; 
my question is for that variable ,is it what we saw in the drawing as the 'Write register' ? 
can i rename next_registers to 'Write register' just for convenience?

**Comment by amichai-bd** [comment]
That is the wrong definition..
logic [31:0] next_registers [31:0]; is correct.
Note: this is a 2 dimentinal array.
It has 32 entires - and each entry is 32 bit.

So this line:
```next_registers[write_ptr] = write_data_reg;```
Makes sense.
write_ptr - is a 5 bit pointer that chooses 1 of 32 entries.
each entry is 32 bit - and by choosing one of the entries in the register file you can wrote 32 bit into it -> writing the "write_data_reg"

**Comment by kereng1** [comment]
got it ,thanks!
@amichai-bd
